# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  dupl:
    threshold: 150

  errcheck:
    check-type-assertions: true
    check-blank: false

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  exhaustive:
    check-generated: false
    default-signifies-exhaustive: true

  gocyclo:
    min-complexity: 15

  godot:
    scope: declarations
    capital: false

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/watzon/alyx

  mnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - "0"
      - "1"
      - "2"
      - "3"
      - "10"
      - "32"
      - "64"
      - "100"
      - "1000"
      - "0o644"
      - "0o755"
      - "8090"
    ignored-functions:
      - "strconv.ParseInt"
      - "strconv.ParseFloat"
      - "strconv.FormatInt"
      - "strconv.FormatFloat"
      - "strings.SplitN"
      - "os.WriteFile"
      - "os.MkdirAll"

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for most cases

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  staticcheck:
    checks:
      - all

  stylecheck:
    checks:
      - all
      - -ST1000  # Package comments
      - -ST1003  # MixedCaps

  unparam:
    check-exported: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gosec
        - mnd
        - gochecknoinits
        - gocyclo
        - predeclared

    # Exclude some linters from running on generated files
    - path: generated
      linters:
        - all

    # Allow err shadowing in error handling blocks
    - linters:
        - govet
      text: "shadow: declaration of \"err\""

    # Allow init functions in CLI and test setup
    - path: internal/cli/
      linters:
        - gochecknoinits

    # Allow predeclared identifiers as param names (common pattern)
    - linters:
        - predeclared
      text: "param .* has same name as predeclared identifier"

    # Allow blank imports for SQL drivers
    - path: internal/database/database\.go
      linters:
        - revive
      text: "blank-imports"

    # Allow higher complexity in validation functions
    - path: internal/database/validate\.go
      linters:
        - gocyclo

    # Allow higher complexity in parser
    - path: internal/schema/parser\.go
      linters:
        - gocyclo

    # Allow higher complexity in openapi generation
    - path: internal/openapi/
      linters:
        - gocyclo
        - goconst

    # Allow ValidationErrors naming (established pattern)
    - linters:
        - errname
      text: "ValidationErrors"

    # Allow unused params in interface implementations
    - path: internal/openapi/
      linters:
        - unparam

    # Allow godot exclusions for inline comments
    - linters:
        - godot
      text: "Comment should end in a period"

    # Prealloc is good advice but not critical
    - linters:
        - prealloc
      text: "Consider pre-allocating"

    # Allow some gocritic patterns
    - linters:
        - gocritic
      text: "appendAssign|exitAfterDefer"

    # Allow exhaustive switch warnings where default is handled
    - linters:
        - exhaustive
      text: "missing cases in switch"

    # Allow some gosec warnings
    - linters:
        - gosec
      text: "G306"

    # Allow config function naming
    - path: internal/config/loader\.go
      linters:
        - revive
      text: "ConfigFilePath"

    # Allow errorlint issues in existing error handling code
    - linters:
        - errorlint
      text: "comparing with|type assertion|non-wrapping"

    # Allow goconst for test fixtures
    - path: _test\.go
      linters:
        - goconst

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
