<script lang="ts">
  import type { Field } from '$lib/api/client';
  import StringField from './StringField.svelte';
  import TextField from './TextField.svelte';
  import NumberField from './NumberField.svelte';
  import BooleanField from './BooleanField.svelte';
  import DateField from './DateField.svelte';
  import JsonField from './JsonField.svelte';
  import BlobField from './BlobField.svelte';
  import ReferenceField from './ReferenceField.svelte';
  import EmailField from './EmailField.svelte';
  import UrlField from './UrlField.svelte';
  import SelectField from './SelectField.svelte';
  import RelationTypeField from './RelationTypeField.svelte';
  import TypeIcon from 'lucide-svelte/icons/type';
  import FileTextIcon from 'lucide-svelte/icons/file-text';
  import HashIcon from 'lucide-svelte/icons/hash';
  import ToggleLeftIcon from 'lucide-svelte/icons/toggle-left';
  import CalendarIcon from 'lucide-svelte/icons/calendar';
  import BracesIcon from 'lucide-svelte/icons/braces';
  import ImageIcon from 'lucide-svelte/icons/image';
  import KeyIcon from 'lucide-svelte/icons/key';
  import LinkIcon from 'lucide-svelte/icons/link';
  import MailIcon from 'lucide-svelte/icons/mail';
  import ListIcon from 'lucide-svelte/icons/list';
  import CalendarDaysIcon from 'lucide-svelte/icons/calendar-days';

  interface Props {
    field: Field;
    value: any;
    errors?: string[];
    disabled?: boolean;
  }

  let { field, value = $bindable(), errors, disabled = false }: Props = $props();

  // Check if this field has a foreign key reference
  const hasReference = $derived(!!field.references);

  function getFieldIcon(type: string, hasRef: boolean) {
    if (hasRef) return LinkIcon;
    switch (type) {
      case 'string': return TypeIcon;
      case 'text': 
      case 'richtext': return FileTextIcon;
      case 'int':
      case 'float': return HashIcon;
      case 'bool': return ToggleLeftIcon;
      case 'timestamp': return CalendarIcon;
      case 'date': return CalendarDaysIcon;
      case 'json': return BracesIcon;
      case 'blob': return ImageIcon;
      case 'uuid': return KeyIcon;
      case 'email': return MailIcon;
      case 'url': return LinkIcon;
      case 'select': return ListIcon;
      case 'relation': return LinkIcon;
      default: return TypeIcon;
    }
  }

  const Icon = $derived(getFieldIcon(field.type, hasReference));
</script>

<div class="rounded-lg bg-background border p-4 {errors?.length ? 'border-destructive' : 'border-border'}">
  <div class="flex items-center gap-2 mb-3">
    <Icon class="h-3.5 w-3.5 {errors?.length ? 'text-destructive' : 'text-muted-foreground'}" />
    <span class="text-xs font-medium uppercase tracking-wide {errors?.length ? 'text-destructive' : 'text-muted-foreground'}">
      {field.name}
    </span>
    {#if field.references}
      <span class="text-xs text-muted-foreground">→ {field.references}</span>
    {/if}
    {#if !field.nullable}
      <span class="text-xs text-destructive">*</span>
    {/if}
  </div>

  <div class="field-content">
    {#if hasReference}
      <ReferenceField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'string'}
      <StringField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'text'}
      <TextField {field} bind:value {errors} {disabled} richText={false} />
    {:else if field.type === 'richtext'}
      <TextField {field} bind:value {errors} {disabled} richText={true} />
    {:else if field.type === 'int' || field.type === 'float'}
      <NumberField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'bool'}
      <BooleanField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'timestamp'}
      <DateField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'date'}
      <DateField {field} bind:value {errors} {disabled} dateOnly />
    {:else if field.type === 'json'}
      <JsonField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'blob'}
      <BlobField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'uuid'}
      <StringField {field} bind:value {errors} {disabled} isAutoGenerated={field.default === 'auto'} />
    {:else if field.type === 'email'}
      <EmailField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'url'}
      <UrlField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'select'}
      <SelectField {field} bind:value {errors} {disabled} />
    {:else if field.type === 'relation'}
      <RelationTypeField {field} bind:value {errors} {disabled} />
    {:else}
      <p class="text-sm text-destructive">Unsupported field type: {field.type}</p>
    {/if}
  </div>
</div>

<style>
  .field-content :global(.space-y-2) {
    --space-y-reverse: 0;
    margin-top: 0;
    margin-bottom: 0;
  }

  .field-content :global(label) {
    display: none;
  }
</style>
