<script lang="ts">
  import { Input } from '$lib/components/ui/input';
  import * as Select from '$lib/components/ui/select';
  import type { Field } from '$lib/api/client';

  interface Props {
    field: Field;
    value: string;
    errors?: string[];
    disabled?: boolean;
    isAutoGenerated?: boolean;
  }

  let { field, value = $bindable(), errors, disabled = false, isAutoGenerated = false }: Props = $props();

  const maxLength = $derived(field.validate?.maxLength as number | undefined);
  const enumValues = $derived(field.validate?.enum as string[] | undefined);
  const format = $derived(field.validate?.format as string | undefined);
  const charCount = $derived(value?.length || 0);
  
  function getPlaceholder(): string {
    if (isAutoGenerated) {
      const typeLabel = field.type.toUpperCase();
      return `Auto (${typeLabel})`;
    }
    if (field.nullable) return 'Optional';
    return 'Required';
  }
</script>

{#if enumValues}
  <Select.Root type="single" bind:value disabled={disabled}>
    <Select.Trigger id={field.name} class="w-full">
      {value || `Select ${field.name}`}
    </Select.Trigger>
    <Select.Content>
      {#each enumValues as option}
        <Select.Item value={option}>{option}</Select.Item>
      {/each}
    </Select.Content>
  </Select.Root>
  {#if errors?.length}
    <p class="text-sm text-destructive mt-2">{errors[0]}</p>
  {/if}
{:else}
  <Input
    id={field.name}
    type={format === 'email' ? 'email' : format === 'url' ? 'url' : 'text'}
    bind:value
    {disabled}
    placeholder={getPlaceholder()}
    maxlength={maxLength}
    class={errors?.length ? 'border-destructive' : ''}
  />
  {#if isAutoGenerated && !value}
    <p class="text-xs text-muted-foreground mt-1.5">Will be generated automatically if left empty</p>
  {:else if maxLength}
    <p class="text-xs text-muted-foreground mt-1.5">{charCount}/{maxLength} characters</p>
  {/if}
  {#if errors?.length}
    <p class="text-sm text-destructive mt-1.5">{errors[0]}</p>
  {/if}
{/if}
