version: 1

collections:
  users:
    fields:
      id:
        type: uuid
        primary: true
        default: auto
      name:
        type: string
      email:
        type: string
        unique: true
      created_at:
        type: timestamp
        default: now
