version: 1

functions:
  hello-node:
    runtime: node
    entrypoint: index.js
    description: Simple Node.js function demonstrating JSON stdin/stdout protocol

  hello-python:
    runtime: python
    entrypoint: index.py
    description: Simple Python function demonstrating JSON stdin/stdout protocol

  hello-deno:
    runtime: deno
    entrypoint: index.ts
    description: Simple Deno function demonstrating JSON stdin/stdout protocol

  hello-typescript:
    runtime: node
    entrypoint: dist/index.js
    description: TypeScript function demonstrating build configuration for production deployment
    timeout: 30s
    memory: 128mb
    build:
      command: npm
      args: ["run", "build"]
      watch: ["*.ts"]
      output: dist/index.js

  file-info:
    runtime: python
    entrypoint: index.py
    description: Analyzes uploaded files and returns metadata (size, hashes, text preview)
    sample_input:
      _files: []

collections:
  users:
    fields:
      id:
        type: uuid
        primary: true
        default: auto
      email:
        type: string
        unique: true
      name:
        type: string
      created_at:
        type: timestamp
        default: now
